---
apiVersion: v1
kind: Pod
metadata:
  labels: ~
  name: init-pod
spec:
  volumes:
       - name: shared-vol
         emptyDir: {}
  containers:
    -
      image: nginx
      name: main-cont
      ports:
        -
          containerPort: 80
      volumeMounts:
        - name: shared-vol
          mountPath: /usr/share/nginx/html
  initContainers:
    - name: init-cont
      image: busybox:latest
      command: ["wget"]
      args: ["-O", "/work-dir/index.html", "http://www.google.com" ]
      volumeMounts:
        - name: shared-vol
          mountPath: "/work-dir"
      
